### ISSUE TITLE
could be used for detection task

### ISSUE THREAD

**Issue by GallonDeng** [alinlab/M2m#1]
great work! 
The proposed method can be easily used for classification task. Could be it used for detection task? If so, it will be fantastic.

**Comment by bbuing9** [comment]
Thanks for your interest in our work!

We haven’t tried so far, but we agree that detection is also an important task in the context of a class-imbalanced setting, and it would be a definitely interesting future work to apply our method on this task.

Object detection differs to classification mainly on predicting bounding boxes, and one may consider to design a M2m translation objective for bounding boxes. I found [[1](https://arxiv.org/abs/1907.10310)] can be somewhat related regarding this.

Hope it helps you.

[1] Haichao Zhang and Jianyu Wang. Toward Adversarially Robust Object Detection. ICCV 2019.
