### ISSUE TITLE
train M2m

### ISSUE THREAD

**Issue by wangjl1993** [alinlab/M2m#2]
great work! 
it seems to should add "--resume" when training M2m. (load ckpt_g)  friendly warning.
 by the way, do you apply M2m on larger dataset, such as  Imagenet?

**Comment by wangjl1993** [comment]
I found the Imagenet experiment in supplementary material~ lol

**Comment by bbuing9** [comment]
Hi, it's nice to hear that you found the experimental results of Imagenet!  

Also, as M2m training requires pre-trained classifier g, "--resume" option should be added to apply it correctly. 

But, regarding the warning message about "--resume", I can't find such a message in my environment when I turn off that option. 

Can you tell me about it in more detail? Then, I'll update the codes more clearly. Thanks!

**Comment by lipingcoding** [comment]
hi, @ bbuing9. According to your reply and source code, I think the command provided in README for "Train another network f using M2m with the pre-trained g" should add --resume option

**Comment by bbuing9** [comment]
Thanks for the nice suggestion, @lipingcoding! For clarification, I have updated both README and run.sh by adding --resume option.
