### ISSUE TITLE
Guidence is needed to reproduce the results ? ?

### ISSUE THREAD

**Issue by sagheer-ahmed** [alinlab/M2m#3]
i have recently learnt python and went through the some MOOCS of machine learning and deep learning. I have downloaded the whole code from this site.
Any one kindly guide me how to run the code and reproduce the results ??

**Comment by bbuing9** [comment]
For reproducing the results, we have uploaded the corresponding shell script (run.sh). So, I recommend you to run codes with it one by one. Thanks :)
