### ISSUE TITLE
How to reproduce the results on CIFAR10 and CIFAR100?

### ISSUE THREAD

**Issue by SodaCoder** [alinlab/M2m#4]
Hello All,

This is Sourav Das, currently working as a Project-Linked Person at Indian Statistical Institute, Kolkata.

I went through your CVPR 2020 paper, titled "M2m: Imbalanced Classification via Major-to-minor Translation" and would like to reproduce the result on CIFAR10 and CIFAR100 datasets.

I cloned the GitHub repo https://github.com/alinlab/M2m but I don't know
1. In which path to keep the CIFAR10 or CIFAR100 datasets?
2. In which format should the datasets be present?
3. Will it run with CIFAR10 and CIFAR100 datasets, directly downloaded from the site: https://www.cs.toronto.edu/~kriz/cifar.html or do I need to do some pre-processing to the datasets?

Awaiting an early response from you.

Thanks & Regards,
Sourav Das

**Comment by bbuing9** [comment]
Hi, Sourav. Thanks for the interest in our work! Answers to the questions are as follow:  

1. As you can see "get_imbalanced" function in data_loader.py, which is mainly used in our code for constructing data loader,
we load datasets in the location of DATA_ROOT. It is currently set to "~/data" (see line18). It can be changed to any directory as you want

2 & 3. Our codes are based on pytorch and torchvision, including the part for the construction of datasets. So, please check the details about it on the corresponding page. (https://pytorch.org/docs/1.1.0/torchvision/datasets.html?highlight=cifar)
