### ISSUE TITLE
Could you tell me how you use T-SNE? Thank you!

### ISSUE THREAD

**Issue by sunhappy6900** [alinlab/M2m#7]
Could you tell me how you use T-SNE? Thank you!

**Comment by bbuing9** [comment]
Hi, T-SNE plots (in Figure 4) are obtained as follow:

1. Training the network with the desired method under the target imbalanced ratio, e.g., M2m with \rho=100

2. Then, randomly select N training samples per class which will be plotted using T-SNE. (E.g., N=50 in the paper)

3. Obtaining the "penultimate features", i.e., before the linear classifier, of the selected samples using the trained network 

4. The, plot the obtained features using any T-SNE code, e.g., Multicore-TSNE (https://github.com/DmitryUlyanov/Multicore-TSNE)

Best,
Jaehyung

**Comment by sunhappy6900** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alinlab/M2m"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月18日(星期天) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alinlab/M2m] Could you tell me how you use T-SNE? Thank you! (#7)





 
Hi, T-SNE plots (in Figure 4) are obtained as follow:
  
 
Training the network with the desired method under the target imbalanced ratio, e.g., M2m with \rho=100
 
 
 
Then, randomly select N training samples per class which will be plotted using T-SNE. (E.g., N=50 in the paper)
 
 
 
Obtaining the "penultimate features", i.e., before the linear classifier, of the selected samples using the trained network
 
 
 
The, plot the obtained features using any T-SNE code, e.g., Multicore-TSNE (https://github.com/DmitryUlyanov/Multicore-TSNE)
 
  
Best,
 Jaehyung
