### ISSUE TITLE
Could you provide the processed CelebA-5 dataset?

### ISSUE THREAD

**Issue by hongxin001** [alinlab/M2m#8]
Hi,

Thanks for your interesting work. I'd like to reproduce the experiments on CelebA-5, but it needs to be processed based on the official version as described in your paper. Could you please share a copy of the processed dataset or the script for processing?

Best Regards,
Hongxin

**Comment by hongxin001** [comment]
especially for " port this CelebA to a 5-way classification task by filtering only the samples with five non-overlapping labels about hair colors"

**Comment by bbuing9** [comment]
These parts are now updated. See `./etc/celeb_loader.py`.

Thanks,
Jaehyung
